"""add_is_on_sale_and_sku_to_product_snapshots

Revision ID: 56dc637c376b
Revises: 6dd1d8c40c4c
Create Date: 2026-04-29 12:01:05.126036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56dc637c376b'
down_revision: Union[str, Sequence[str], None] = '6dd1d8c40c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('product_snapshots', sa.Column('sku', sa.String(length=50), nullable=True))
    # server_default='false' backfills existing rows safely before enforcing NOT NULL
    op.add_column('product_snapshots', sa.Column('is_on_sale', sa.Boolean(), nullable=False, server_default='false'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_snapshots', 'is_on_sale')
    op.drop_column('product_snapshots', 'sku')
    # ### end Alembic commands ###
